shifted docs to jeyklly and github pages, and generator to react
shay-te/core-lib pull request #127
Opened 2023-06-20 03:02 UTC by shubham-shay-te

2023-06-20 10:31 UTC, shubham-shay-te commented on website/public/logo192.png
replace with core-lib logog

2023-06-22 13:17 UTC, shay-te requested changes

2023-06-22 13:17 UTC, shay-te commented on docs/_config.yml
> +google_analytics: UA-66296557-1
׳ישif not, edit this value to blank.

2023-06-22 13:22 UTC, shay-te requested changes

2023-06-30 10:27 UTC, shay-te approved these changes

2023-06-30 10:30 UTC, merged