Added util file under core lib generator
shay-te/core-lib pull request #147
Opened 2024-09-02 09:39 UTC by oren-una

Let me know if this is okay

2024-09-02 12:24 UTC, shay-te requested changes

2024-09-02 12:24 UTC, shay-te commented on core_lib_generator/template_core_lib/util/util.py
> +import traceback
please make sure also that the example test is using this file

2024-09-09 05:44 UTC, shubham-shay-te requested changes

2024-09-09 05:44 UTC, shubham-shay-te commented on core_lib_generator/core_lib_generator_from_yaml.py
> +        self._generate_template(f'{self.snake_core_lib_name}/tests/test_data/helpers/util.py',
create a seperate generator for util, `TestUtilGenerateTemplate` this class will be responsible to generate the util and replace the template strings with the actual core lib name

2024-09-09 05:44 UTC, shubham-shay-te commented on core_lib_generator/config_collectors/data_access.py
> -            conn = entity['db_connection']
revert `git rm --cached path/to/file`

2024-09-16 06:21 UTC, shubham-shay-te requested changes

2024-09-16 06:21 UTC, shubham-shay-te commented on core_lib_generator/template_core_lib/tests/test_template.py
> +        self.template_snake_core_lib = sync_create_start_core_lib()
can we also update the `core_lib_generator/file_generators/test_generator.py` to remove any updates we are not making

2024-09-16 06:21 UTC, shubham-shay-te commented on core_lib_generator/file_generators/test_util_generator.py
> +        return 'template_core_lib/tests/test_data/helpers/util.py'
`'template_core_lib/tests/test_data/helpers/util.py'` can you please check if the file exists here and you have pushed I don't see the file under this path in the PR

2024-09-16 06:21 UTC, shubham-shay-te commented on core_lib_generator/template_core_lib/util/util.py
this file should be under `template_core_lib/tests/test_data/helpers/util.py`

2024-09-16 06:21 UTC, shubham-shay-te commented on core_lib_generator/file_generators/test_util_generator.py
> +        template_content = template_content.replace('# template core_lib_instance', import_instance_string)
can you verify if the util is using this import or it is needed here, I don't see this string the util file in the template

2024-09-16 09:28 UTC, oren-una commented on core_lib_generator/template_core_lib/util/util.py
The file is there, just under core_lib_generator folder

2024-09-16 10:48 UTC, closed without merging