tests and doc for default registry
shay-te/core-lib pull request #36
Opened 2022-02-09 12:25 UTC by shubham-shay-te

2022-02-10 04:04 UTC, shay-te commented
good work thank you

2022-02-10 04:04 UTC, shay-te approved these changes

2022-02-10 04:04 UTC, shay-te commented on website/docs/default_registry.md
> +registry_factory = DefaultRegistry(str)
please store in the registry something more real other then just a string.

2022-02-10 06:44 UTC, shubham-shay-te commented on website/docs/default_registry.md
> +`name` is type `str`, sets the name of the registry entry passed to the function.
yes, `key` will make sense.

2022-02-10 09:24 UTC, shay-te commented on website/docs/default_registry.md
> +user_name = 'Jon Doe'
`DefaultRegistry` will be used to store more complex things and not strings. 
please take a look at `CacheRegistry` class. 
plase create a dummy class called `Customer`. 

+ show how to create the `CustomerRegistry`  take this example from the  CacheRegistry

2022-02-10 14:46 UTC, shay-te requested changes

2022-02-10 14:46 UTC, shay-te commented on tests/test_default_registry.py
> +        self.assertEqual(registry_factory.get(), dict_1)
same test for customer

2022-02-10 14:46 UTC, shay-te commented on tests/test_default_registry.py
> +        registry_factory.register('integer', integer)
int_registry

2022-02-10 14:46 UTC, shay-te commented on website/docs/default_registry.md
> +`key` is type `str`, sets the key of the registry entry passed to the function.
this key is unique. 
registering the same key again wioll raise an ValueError

2022-02-13 22:02 UTC, shay-te approved these changes

2022-02-16 06:35 UTC, merged