generate alembic funcs in main class
shay-te/core-lib pull request #72
Opened 2022-04-11 11:42 UTC by shubham-shay-te

2022-04-11 17:15 UTC, shay-te requested changes

2022-04-11 17:15 UTC, shay-te commented on core_lib_generator/file_generators/core_lib_class_generator.py
> +        func_list.append(static_method_str.rjust(len(static_method_str) + 4))
thank you very much, nice solution but it's complex.  try to make this straightforward and simple. 
another comment. 
4 is repeating itself. remember that when a value repeats more than once it's a variable.? 
tab_size = 4.

BUT this solution is complex. 
try this please

use `\t` instead. read about \t

f`'\t{install_func_str}'`

2022-04-12 18:04 UTC, shay-te requested changes

2022-04-12 18:04 UTC, shay-te commented on core_lib_generator/file_generators/core_lib_class_generator.py
> +tab_spaces_8 = 8
this is that character in a single tab? if its 2 tabs then call 
`add_tab_spaces(str, 2)` (see suggestion below)

2022-04-13 05:25 UTC, shubham-shay-te commented on core_lib_generator/generator_utils/formatting_utils.py
> +def add_tab_spaces(string: str, tab_size: int = 4) -> str:
yeah, looks good, thankyou

2022-04-21 06:09 UTC, shay-te approved these changes

2022-04-21 09:23 UTC, merged